### PR TITLE
[MAJOR] Implemented frontend for schedule meeting (create, view)

### PR DESCRIPTION
**Pull request by nasaku898**
#200 

Currently implemented view and create meeting. I will implement update and delete next sprint.
In addition, the calendar is taking the full page, but I might shrink it later.
image
image
image
image
image

### CODE REVIEW

**Review by Manraj45 — CHANGES_REQUESTED** [review]
For the date, start and end input, there is no star that indicates that it is a required input. Also, when the user is in the agenda view, can the user add an event or is it only for the calendar view? Also, for the next sprint, we should also change the color of the calendar to match the rest of the app: https://stackoverflow.com/questions/34587067/change-color-of-react-big-calendar-events

**Review by bowsong — CHANGES_REQUESTED** [review]
Could you rename the CalendarAPI file to EventAPI. All it does is call the event routes and it would cause less confusion in the future.

**Comment by nasaku898** [comment]
@Manraj45 
you cannot create in agenda view.
image

**Comment by nasaku898** [comment]
> Could you rename the CalendarAPI file to EventAPI. All it does is call the event routes and it would cause less confusion in the future.

Fair point, I have updated the file name.

**Review by Manraj45 — APPROVED** [review]
Good Job!

**Review by bowsong — APPROVED** [review]
Looks good to me

**Pull request merged**
