### PR TITLE
[MAJOR] Implement landing page

### LINKED ISSUE #162: Implement landing page

### PR DESCRIPTION
**Pull request by bowsong**
closes #162 
image

### CODE REVIEW

**Review by nasaku898 — APPROVED** [review]
Cool blur effect

**Review by nasaku898 — COMMENTED** [review]
Cool blur effect! There's a small code smell you can fix before merging.

**Review by Manraj45 — CHANGES_REQUESTED** [review]
Everything seems good. You just need to fix the code smell.

**Review by Manraj45 — APPROVED** [review]
Good Job!

**Pull request merged**
