### PR TITLE
Implement delete update and confirmation for schedule meeting

### LINKED ISSUE #240: Implement update and delete for schedule meeting in frontend

### PR DESCRIPTION
**Pull request by nasaku898**
close #240 
image

### CODE REVIEW

**Review by Mnx458 — APPROVED** [review]
Good

**Review by huangs08 — APPROVED** [review]

**Comment by nasaku898** [comment]
> Could you add a bit of spacing here: image

Here's the updated UI with additional space. That was a good idea. 
image

**Review by Manraj45 — APPROVED** [review]
Good Job!

**Review by jmezaber — APPROVED** [review]
Nice work Simon! Love your implementation of the popup and the colours! Don't forget to change the PR name ;)

**Pull request merged**
