### PR TITLE
[MINOR] Added route guarding to frontend.

### LINKED ISSUE #134: Restrict routes and endpoints of the frontend
Epic/User story #132

### PR DESCRIPTION
**Pull request by Manraj45**
closes #134

### CODE REVIEW

**Review by nasaku898 — APPROVED** [review]
Great work and thank you for updating the test and reducing code duplication.

**Review by bowsong — APPROVED** [review]
Intercepts look good and tests look good

**Review by Mnx458 — APPROVED** [review]
Project route in the frontend looks good to me

**Review by davidthai0387 — APPROVED** [review]
LogHours looks good!

**Pull request merged**
