### PR TITLE
[MINOR] Implementing automatic paid amount for LogHours.

### LINKED ISSUE #119: Improvement request for logged hours feature from PO
- Center the log hours component to center of screen.

### PR DESCRIPTION
**Pull request by davidthai0387**
closes #119 

Small PR for automatic paidAmount calculation based on hoursWorked.

image

The rest of the features are related to the new logged hours page and will be done with the other task.

### CODE REVIEW

**Review by nasaku898 — DISMISSED** [review]
Looks good! Don't forget to the update your PR title to the convention we set before merging.

**Review by Mnx458 — DISMISSED** [review]
looks good

**Review by Manraj45 — CHANGES_REQUESTED** [review]
Fix warning in TaskService.test.ts. Also, rename the PR to follow the convention. Fix merge conflicts.

**Review by Manraj45 — APPROVED** [review]
Good job!

**Review by nasaku898 — APPROVED** [review]

**Pull request merged**
