### PR TITLE
[MINOR] Created Swagger for Call endpoints.

### LINKED ISSUE #189: Create Swagger for Call endpoint
Epic/User story #123

### PR DESCRIPTION
**Pull request by huangs08**
closes #189

### CODE REVIEW

**Review by nasaku898 — DISMISSED** [review]

**Comment by huangs08** [comment]
@nasaku898 The changes do not affect the frontend as they are not currently being called.

**Comment by huangs08** [comment]
Screenshot 2022-01-27 160822

**Review by nasaku898 — APPROVED** [review]

**Review by Manraj45 — CHANGES_REQUESTED** [review]
There are some endpoints where the 400 description is wrong.

**Review by Manraj45 — APPROVED** [review]
Good job!

**Comment by nasaku898** [comment]
Don't forget to put `Minor` in capital

**Review by jmezaber — APPROVED** [review]
Good job

**Pull request merged**
