### PR TITLE
[MAJOR] Adding frontend and backend test for transaction feature #198

### LINKED ISSUE #198: Transaction project feature test
e2e test
jest testing
diagram

### PR DESCRIPTION
**Pull request by Mnx458**
closes #198

### CODE REVIEW

**Review by davidthai0387 — APPROVED** [review]
Looks good, good job!

**Review by bowsong — APPROVED** [review]
Looks good

**Comment by Mnx458** [comment]
> Looks good, good job!

thank you

**Comment by Mnx458** [comment]
> Looks good

thank you

**Pull request merged**
